[package]
name = "tool-net-ffi"
version = "0.1.0"
edition = "2021"

[dependencies]
tool-net = { path = "../tool-net" }
toolbase = { path = "../toolbase" }

[lib]
path = "src/lib.rs"
crate-type = ["cdylib", "staticlib"]

