[workspace]
resolver = "2"
members = [
  "crates/forgeffi-base",
  "crates/forgeffi-net",
  "crates/forgeffi-net-ffi",
  "crates/forgeffi-fs",
  "crates/forgeffi-fs-ffi",
  "crates/forgeffi-sys",
  "crates/forgeffi-sys-ffi",
  "crates/forgeffi",
  "crates/forgeffi-ffi",
  "crates/xtask",
]

