[package]
name = "forgeffi-net-ffi"
version = "0.1.0"
edition = "2024"

[dependencies]
forgeffi-base = { path = "../forgeffi-base" }
forgeffi-sys = { path = "../forgeffi-sys" }
serde_json = "1"

[lib]
path = "src/lib.rs"
crate-type = ["rlib", "cdylib", "staticlib"]
