[package]
name = "forgeffi-fs-ffi"
version = "0.1.0"
edition = "2024"

[dependencies]
forgeffi-fs = { path = "../forgeffi-fs" }
forgeffi-base = { path = "../forgeffi-base" }

[lib]
path = "src/lib.rs"
crate-type = ["rlib", "cdylib", "staticlib"]

