[package]
name = "tool-sys-ffi"
version = "0.1.0"
edition = "2021"

[dependencies]
tool-sys = { path = "../tool-sys" }
toolbase = { path = "../toolbase" }

[lib]
path = "src/lib.rs"
crate-type = ["cdylib", "staticlib"]

