[package]
name = "forgeffi-sys"
version = "0.1.0"
edition = "2024"

[dependencies]
forgeffi-base = { path = "../forgeffi-base" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[lib]
path = "src/lib.rs"

