[package]
name = "forgeffi-sys-ffi"
version = "0.1.0"
edition = "2024"

[dependencies]
forgeffi-sys = { path = "../forgeffi-sys" }
forgeffi-base = { path = "../forgeffi-base" }

[lib]
path = "src/lib.rs"
crate-type = ["cdylib", "staticlib"]

